server:
  port: 9002

spring:
  datasource:
    url: jdbc:mariadb://192.168.118.86:3308/your_db
    username: root
    password: password1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: false
        jdbc:
          batch_size: 1000
        dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.MariaDBDialect



#####File Configurations#####
file:
  header: HEADER
  trailer: TRAILER
  detail: DETAIL

  baseFilePath: C:\Users\S03\Desktop\DBS\BGCPFILES


  databaseType: CLS_WAA.dbo
  threadCount: 5
  batchsize: 1000
