server:
  port: 9002

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;TrustServerCertificate=true;databaseName=CLS_WAA;
    username: sqluser
    password: password1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: false
        jdbc:
          batch_size: 1000
        dialect: org.hibernate.dialect.SQLServerDialect

#####File Configurations#####
file:
  header: HEADER
  trailer: TRAILER
  detail: DETAIL

  baseFilePath: C:\Users\S03\Desktop\DBS\BGCPFILES


  databaseType: CLS_WAA.dbo
  threadCount: 5
  batchsize: 1000
