server:
  port: 9002

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bgcp
    username: root
    password: root123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        generate_statistics: false
        jdbc:
          batch_size: 1000
        dialect: org.hibernate.dialect.MariaDBDialect
    database-platform: org.hibernate.dialect.MariaDBDialect



#####File Configurations#####
file:
  header: HEADER
  trailer: TRAILER
  detail: DETAIL

  baseFilePath: C:\Projects\BGCPDataVerifier\src\main\resources\BGCPFILES


  databaseType: CLS_WAA.dbo
  threadCount: 5
  batchsize: 1000

app:
  GCXPSTR:
    targetAttributes: INXEXTR_CIS_PRODUCT_CODE,INXEXTR_ACC_NUMBER,INXEXTR_SUB_LOAN_NUMBER